#!/usr/bin/env python3
"""Generate one <SSS>.par2 per simulation from a list file and a template.

Reads a whitespace-separated list (default 'list'), one simulation per line:

    SSS                              BBB           CCC PPP
    AbacusAurora_emulmax_cCCC_phPPP  EmulatorMax   000 300

SSS is itself a template: BBB/CCC/PPP are substituted into it to give the
SimName, which is also the output filename (<SimName>.par2).  Then all four
tokens are substituted into template.par2 to produce the file.

Substitution is plain, case-sensitive text replacement -- no regex, no word
boundaries -- done in ONE pass, so a value that happens to contain a token
(e.g. a SimName containing 'CCC') is never rescanned and re-substituted.

An existing output file is not overwritten unless -f is given; it is reported
and skipped, so re-running after adding rows to the list only creates what is
missing.

Usage:
    ./make_par2.py                    # list, template.par2, write
    ./make_par2.py -n                 # dry run: say what would be written
    ./make_par2.py -f                 # overwrite existing .par2 files
    ./make_par2.py -fn                # dry run, showing what -f would replace
    ./make_par2.py mylist -t alt.par2
"""

import argparse
import re
import sys
from pathlib import Path

# Order here is the column order in the list file.  SSS is the SimName template
# and is resolved from the others before being substituted into template.par2.
COLUMNS = ['SSS', 'BBB', 'CCC', 'PPP']


def substitute(text, values):
    """Replace every token in `values` simultaneously, case-sensitively.

    One pass via a single alternation, rather than a chain of str.replace calls:
    sequential replacement would rescan text we just inserted, so a value
    containing another token would get mangled.  Tokens are matched literally.
    """
    pattern = re.compile('|'.join(re.escape(k) for k in values))
    return pattern.sub(lambda m: values[m.group(0)], text)


def read_rows(listfn):
    """Yield (lineno, [fields]) for the data lines of the list file.

    Blank lines and comments are skipped; a '#' anywhere starts a comment, so a
    trailing note on a data line is fine.  Returns rows with the wrong number of
    columns too -- the caller reports them, so one malformed line doesn't hide
    the rest.
    """
    for lineno, raw in enumerate(listfn.read_text().splitlines(), start=1):
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        yield lineno, line.split()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('list', nargs='?', default='list',
                    help='list file, one simulation per line (default: %(default)s)')
    ap.add_argument('-t', '--template', default='template.par2',
                    help='template to substitute into (default: %(default)s)')
    ap.add_argument('-n', '--dry-run', action='store_true',
                    help='report what would be written, without writing')
    ap.add_argument('-f', '--force', action='store_true',
                    help='overwrite existing .par2 files instead of skipping them')
    args = ap.parse_args()

    listfn = Path(args.list)
    templatefn = Path(args.template)
    for fn in (listfn, templatefn):
        if not fn.is_file():
            sys.exit(f'{sys.argv[0]}: no such file: {fn}')
    template = templatefn.read_text()
    outdir = listfn.parent

    written = skipped = replaced = 0
    errors = []
    seen = {}   # SimName -> lineno that first produced it

    for lineno, fields in read_rows(listfn):
        if len(fields) != len(COLUMNS):
            errors.append(f'line {lineno}: expected {len(COLUMNS)} columns '
                          f'({" ".join(COLUMNS)}), got {len(fields)}: {" ".join(fields)}')
            continue
        values = dict(zip(COLUMNS, fields))

        # SSS is itself a template; resolve it before it becomes a substitution value.
        simname = substitute(values['SSS'], {k: values[k] for k in COLUMNS if k != 'SSS'})
        values['SSS'] = simname

        if simname in seen:
            errors.append(f'line {lineno}: {simname} was already generated by '
                          f'line {seen[simname]}; skipping the duplicate')
            continue
        seen[simname] = lineno

        outfn = outdir / f'{simname}.par2'
        overwriting = outfn.exists()
        if overwriting and not args.force:
            print(f'exists, skipping:  {outfn}')
            skipped += 1
            continue

        if args.dry_run:
            print(f'would {"replace" if overwriting else "write":8s}   {outfn}')
        else:
            outfn.write_text(substitute(template, values))
            print(f'{"replaced" if overwriting else "wrote":9s}          {outfn}')
        written += 1
        replaced += overwriting

    verb = 'would write' if args.dry_run else 'wrote'
    detail = f' ({replaced} overwritten)' if replaced else ''
    print(f'\n{verb} {written}{detail}, skipped {skipped} existing, {len(errors)} problem(s)')
    for e in errors:
        print(f'  {e}', file=sys.stderr)
    return 1 if errors else 0


if __name__ == '__main__':
    sys.exit(main())
