#!/usr/bin/env python3
"""Create a cosm.def from the CLASS.ini in a cosmology directory.

Reads <dir>/CLASS.ini and writes <dir>/cosm.def containing the Abacus cosmology
parameters, converting from the CLASS parameterization. The conversion math
mirrors read_table() in AbacusSummit/util/create_par.py; here we only emit the
cosmology block (not a full .par2).

Usage:
    python make_cosm_def.py <dir> [<dir> ...]

e.g.  python make_cosm_def.py abacus_cosm117
      for d in abacus_cosm*/; do python make_cosm_def.py "$d"; done
"""

import argparse
import re
import sys
from pathlib import Path


def parse_class_ini(path):
    """Parse a CLASS .ini into {name: value_string}, dropping comments/blanks.

    Follows CLASS syntax: 'name = value', optional quotes around the name, and
    '#' starting a comment (whole-line or trailing).
    """
    params = {}
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith('#') or '=' not in s:
            continue
        name, val = re.split(r'\s*=\s*', s, maxsplit=1)
        name = name.strip().strip('\'"')
        if '#' in val:
            val = val[:val.index('#')]
        val = val.strip()
        if val == '':
            continue
        params[name] = val
    return params


def sum_floats(val):
    """Sum a possibly comma-separated list of floats (e.g. multiple ncdm species)."""
    return sum(float(p) for p in re.split(r'\s*,\s*', val) if p != '')


def make_cosm_def(cosm_dir):
    cosm_dir = Path(cosm_dir).resolve()
    ini = cosm_dir / 'CLASS.ini'
    if not ini.is_file():
        sys.exit(f"error: no CLASS.ini in {cosm_dir}")

    p = parse_class_ini(ini)

    def req(k):
        if k not in p:
            sys.exit(f"error: {ini} is missing required key '{k}'")
        return p[k]

    # Hubble: CLASS files use 'h', but accept 'H0' as a fallback.
    if 'h' in p:
        h = float(p['h'])
    elif 'H0' in p:
        h = float(p['H0']) / 100.0
    else:
        sys.exit(f"error: {ini} has neither 'h' nor 'H0'")

    omega_b = float(req('omega_b'))
    omega_cdm = float(req('omega_cdm'))
    omega_ncdm_sum = sum_floats(req('omega_ncdm'))

    # Derived (see read_table): densities are omega_x / h^2; the smooth (ncdm)
    # component is treated as Omega_Smooth.
    Omega_M = (omega_b + omega_cdm + omega_ncdm_sum) / h**2
    Omega_Smooth = omega_ncdm_sum / h**2
    H0 = h * 100.0

    cosm_name = cosm_dir.name  # e.g. abacus_cosm117
    pk = f'"$ABACUS$/prod/Cosmologies/{cosm_name}/CLASS_power"'

    lines = [
        f"# Abacus cosmology parameters for {cosm_name}, converted from CLASS.ini",
        f"# Generated by make_cosm_def.py -- do not edit by hand; regenerate instead.",
        "",
        "# Renamed from CLASS w0_fld / wa_fld:",
        f"w0 = {req('w0_fld')}",
        f"wa = {req('wa_fld')}",
        "",
        "# Derived from h and the omega_* densities:",
        f"H0 = {H0:.10g}",
        f"Omega_M = {Omega_M:f}",
        f"Omega_Smooth = {Omega_Smooth:f}",
        "Omega_K = 0.0",
        "Omega_DE = 1.0-@Omega_M@",
        "",
        "# Copied straight from CLASS.ini:",
        f"N_ur = {req('N_ur')}",
        f"N_ncdm = {req('N_ncdm')}",
        f"n_s = {req('n_s')}",
        f"omega_b = {req('omega_b')}",
        f"omega_cdm = {req('omega_cdm')}",
        f"omega_ncdm = {req('omega_ncdm')}",
        "",
        f"ZD_Pk_filename = {pk}",
        f"ZD_Pk_file_redshift = 1.0",
        "",
    ]

    out = cosm_dir / 'cosm.def'
    out.write_text("\n".join(lines))
    print(f"wrote {out}  (H0={H0:.10g}  Omega_M={Omega_M:f}  Omega_Smooth={Omega_Smooth:f})")


if __name__ == '__main__':
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('dir', nargs='+', help='cosmology directory containing CLASS.ini')
    args = ap.parse_args()
    for d in args.dir:
        make_cosm_def(d)
