root = abacus_cosm206.
# FLAMINGO PlanckNu0p24Var
omega_b = 0.02235
omega_cdm = 0.1188
h = 0.662
A_s = 2.109e-09
n_s = 0.968
alpha_s = 0.0
N_ur = 2.0328
N_ncdm = 1.0
omega_ncdm = 0.0025768
w0_fld = -1.0
wa_fld = 0.0
