root = abacus_cosm204.
# FLAMINGO PlanckNu0p24Fix
omega_b = 0.022375
omega_cdm = 0.1182
h = 0.673
A_s = 2.101e-09
n_s = 0.966
alpha_s = 0.0
N_ur = 2.0328
N_ncdm = 1.0
omega_ncdm = 0.0025768
w0_fld = -1.0
wa_fld = 0.0
