root = abacus_cosm217.
# 0.12 eV single species; theta_s matched, sigma8_cb = 0.869782
omega_b = 0.02237
omega_cdm = 0.12
h = 0.668
A_s = 2.4641e-09
n_s = 0.9649
alpha_s = 0.0
N_ur = 2.0328
N_ncdm = 1.0
omega_ncdm = 0.0012884
w0_fld = -1.0
wa_fld = 0.0
