root = abacus_cosm200.
# DESI DR2+CMB w0wa best-fit (Garcia-Quintero)
omega_b = 0.02242
omega_cdm = 0.1198
h = 0.6723
A_s = 2.1143e-09
n_s = 0.9713
alpha_s = 0.0
N_ur = 2.0328
N_ncdm = 1.0
omega_ncdm = 0.00064420
w0_fld = -0.824
wa_fld = -0.641
