root = abacus_cosm213.
# massless neutrino; theta_s matched, sigma8_cb = 0.753159
omega_b = 0.02237
omega_cdm = 0.12
h = 0.679
A_s = 1.7528e-09
n_s = 0.9649
alpha_s = 0.0
N_ur = 3.046
N_ncdm = 0.0
omega_ncdm = 0.0
w0_fld = -1.0
wa_fld = 0.0
